### ISSUE TITLE
嘛，大佬，前几天还行的，今天更新完抽卡就不好使了

### ISSUE THREAD

**Issue by ILYSHL** [Cosmos01/Blue_Archive_HoshinoBot#1]
![image](https://user-images.githubusercontent.com/42436917/183858433-fe06d417-4f76-42ce-b4d4-7a6203956dd4.png)
看控制台好像也没毛病
![image](https://user-images.githubusercontent.com/42436917/183858693-517d5da6-6bb0-4b65-8c87-dbc3cae923cf.png)

**Comment by Cosmos01** [comment]
我完整重装了一遍，没遇到这个问题。
我这边上传了一份图片资源和角色卡池配置文件，你替换一下看看。
https://github.com/Cosmos01/Blue_Archive_HoshinoBot/releases/download/res/res.zip

**Comment by Cosmos01** [comment]
之前自动获取图片确实存在一些问题，但是只会影响部分图片。刚刚修复了获取图片的问题，你也可以更新后删除原来的资源文件夹，换成项目里的资源文件

**Comment by ILYSHL** [comment]
嗯，谢谢大佬，已经好了。
也请一直维护www

**Comment by ILYSHL** [comment]
> 之前自动获取图片确实存在一些问题，但是只会影响部分图片。刚刚修复了获取图片的问题，你也可以更新后删除原来的资源文件夹，换成项目里的资源文件

**Comment by ILYSHL** [comment]
> 之前自动获取图片确实存在一些问题，但是只会影响部分图片。刚刚修复了获取图片的问题，你也可以更新后删除原来的资源文件夹，换成项目里的资源文件

嗯，谢谢大佬，已经好了。
也请一直维护www
