### ISSUE TITLE
ba查询功能运行时间太长

### ISSUE THREAD

**Issue by Rinco304** [Cosmos01/Blue_Archive_HoshinoBot#12]
如图：`ba查询`功能运行时间太长导致bot在这期间其他功能都不能使用，只有等待此功能完成后再继续运行(最开始我以为是卡死了)
因为运行时间太长还导致了部分单独挂载插件与hoshino本体断开了连接
![image](https://user-images.githubusercontent.com/75192177/236824066-e7f07b81-47ce-4320-9c6a-8f61579ce764.png)
![P)10$_(9E`LNS4Q~S01)C3K](https://user-images.githubusercontent.com/75192177/236826291-bd6c9834-4391-4e78-8973-c9809aa8e5f1.png)
大佬看到了看能不能优化一下，不知道是不是我的问题但这确实有点花时间（

**Comment by Rinco304** [comment]
> 异步已经加上了。 网络慢的问题我后续把文件放到oss上应该能解决，但是目前我测试浙江和香港访问没感觉比较慢，基本上都不超过5秒

我用的是广州服务器，刚刚再试了一下运行时间是在20秒左右（总不会是我的代理有问题吧...但那是端口代理不访问端口是直接连接），现在加了异步后其他功能正常运行，暂时没问题了，谢谢大佬优化

**Comment by diyigemt** [comment]
既然都上oss为什么不再加个cdn(

**Comment by diyigemt** [comment]
> > 
> 
> 最早我就是上cdn的，然后我域名似乎很快就被部分地区墙了，有什么好办法吗

国内域名要备案，国外域名不稳定，没啥好办法

我自己是国内域名+腾讯云cdn全球加速，很稳定

**Comment by diyigemt** [comment]
1. OSS需要考虑下行流量费用的问题，最好还是OSS+CDN
2. 据我所知国内带宽金贵得很
3. cf目前[这个项目](https://github.com/orgs/ba-archive)的主站就在用，有用户反馈不太行

在流量不大的情况下或许可以考虑vercel? 这里有相关讨论https://github.com/orgs/ba-archive/discussions/97#discussioncomment-4867760
